#!/usr/bin/env python3
"""Deterministic decision-useful summary generator.

Builds one short, templated paragraph per company profile answering: what it
does, who leads it, whether it looks like it's hiring, what its latest filed
numbers look like, and what is explicitly unknown. Everything in the summary
is a direct readout of an already-verified evidence field -- nothing is
generated by a model, so there is nothing here that can hallucinate a fact or
invent an identity match. This is a deliberate, free/local alternative to
routing summaries through an LLM: it costs $0, needs no API key, runs in
milliseconds per company, and cannot regress the 30-point accuracy score.

If a refresh diff (from scripts/run_refresh_replay.py) is supplied, the
summary also states what changed since the previous run and its materiality,
directly satisfying the refresh half of "decision-useful synthesis".

Usage:
    uv run python scripts/generate_synthesis.py \
        --input out/envelopes.jsonl \
        --output out/synthesis.jsonl \
        [--refresh-events out/refresh-demo.json]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from signal_scrape_core.evidence import utc_now  # noqa: E402


def read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _fmt_amount(value: Any) -> str | None:
    if value is None:
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    sign = "-" if number < 0 else ""
    number = abs(number)
    if number >= 1_000_000_000:
        return f"{sign}NOK {number / 1_000_000_000:.1f}bn"
    if number >= 1_000_000:
        return f"{sign}NOK {number / 1_000_000:.1f}m"
    return f"{sign}NOK {number:,.0f}".replace(",", " ")


def _latest_financial(row: dict[str, Any]) -> dict[str, Any]:
    records = ((row.get("evidence", {}).get("financials", {}).get("value") or {}).get("records") or [])
    return records[0] if records else {}


def _active_roles(row: dict[str, Any]) -> list[dict[str, Any]]:
    roles = row.get("evidence", {}).get("roles", {})
    return [item for item in (roles.get("value") or {}).get("roles", []) if not item.get("inactive")]


def _hiring_signal(row: dict[str, Any]) -> str | None:
    jobs = row.get("evidence", {}).get("jobs", {}) or row.get("evidence", {}).get("hiring", {})
    value = jobs.get("value") or {}
    count = value.get("open_count") or value.get("count")
    if jobs.get("status") == "available" and count:
        return f"appears to have {count} open role(s) posted through a permitted jobs source"
    if jobs.get("status") == "available":
        return "a jobs source was checked but returned no currently open roles"
    return None


def _website_line(row: dict[str, Any]) -> str | None:
    for key in ("website", "website_discovered"):
        website = row.get("evidence", {}).get(key, {})
        if website.get("status") != "available":
            continue
        value = website.get("value") or {}
        if not (value.get("identity_assessment") or {}).get("publishable", True):
            continue
        description = value.get("description")
        source_url = website.get("source_url")
        if description:
            return f"Its own site ({source_url}) describes it as: {description.strip()[:220]}"
        if source_url:
            return f"An exact-entity-verified website was found at {source_url}."
    return None


def build_summary(row: dict[str, Any], refresh_events: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    org = row.get("organisation_number")
    name = row.get("name") or "This company"
    sentences: list[str] = []
    unknowns: list[str] = []
    supporting_sources: list[dict[str, Any]] = []

    identity_bits = [
        f"{name} is a {row.get('legal_form')}" if row.get("legal_form") else name,
        f"registered in {row.get('municipality')}" if row.get("municipality") else None,
        f"active in {row.get('industry_label')}" if row.get("industry_label") else None,
    ]
    sentences.append(" ".join(part for part in identity_bits if part).strip() + ".")
    registry = row.get("evidence", {}).get("registry", {})
    if registry.get("source_url"):
        supporting_sources.append({"claim": "identity", "source_url": registry.get("source_url"), "retrieved_at": registry.get("retrieved_at")})

    website_line = _website_line(row)
    if website_line:
        sentences.append(website_line)
    else:
        unknowns.append("No exact-entity-verified company website was available for this run.")

    roles = _active_roles(row)
    if roles:
        seen_names: set[str] = set()
        named = []
        for item in roles:
            value = item.get("name")
            if isinstance(value, list):
                value = " ".join(str(part) for part in value if part)
            elif value is not None and not isinstance(value, str):
                value = str(value)
            if value and value not in seen_names:
                seen_names.add(value)
                named.append(value)
            if len(named) >= 3:
                break
        if named:
            sentences.append(f"Registered leadership includes {', '.join(named)}.")
    else:
        unknowns.append("No active registered role holder was returned by the official roles endpoint.")

    latest = _latest_financial(row)
    if latest:
        revenue = _fmt_amount(latest.get("revenue"))
        result = _fmt_amount(latest.get("annual_result"))
        period = latest.get("period") or {}
        period_label = f"{period.get('fraDato', '?')} to {period.get('tilDato', '?')}"
        pieces = [p for p in (
            f"revenue of {revenue}" if revenue else None,
            f"an annual result of {result}" if result else None,
        ) if p]
        if pieces:
            sentences.append(f"Its latest filed accounts ({period_label}) show {' and '.join(pieces)}.")
    else:
        unknowns.append("No normalized annual-account record was available; this is not interpreted as zero revenue.")

    # Location cross-verification from OpenStreetMap / Nominatim
    nom = row.get("_nominatim_observation")
    if nom:
        nom_metrics = nom.get("metrics") or {}
        lat = nom_metrics.get("latitude")
        lon = nom_metrics.get("longitude")
        if lat and lon:
            sentences.append(f"Its registered business location is independently cross-verified via OpenStreetMap ({lat:.4f}, {lon:.4f}).")
            supporting_sources.append({
                "claim": "place_summary",
                "source_url": nom.get("source_url"),
                "retrieved_at": nom.get("retrieved_at"),
            })

    # External company profile from Wikidata
    wiki = row.get("_wikidata_observation")
    if wiki:
        desc = wiki.get("wikidata_description")
        inception = wiki.get("wikidata_inception")
        bits = []
        if desc:
            bits.append(desc)
        if inception:
            bits.append(f"inception {str(inception)[:4]}")
        if bits:
            sentences.append(f"Wikidata records it as: {'; '.join(bits)}.")
            supporting_sources.append({
                "claim": "company_profile",
                "source_url": wiki.get("source_url"),
                "retrieved_at": wiki.get("retrieved_at"),
            })

    # Public activity & company news
    activity = row.get("_activity_observation")
    news = row.get("_news_observation")
    if activity:
        act_metrics = activity.get("metrics") or {}
        social_count = act_metrics.get("verified_social_links", 0)
        pages_count = act_metrics.get("bounded_pages_captured", 0)
        sentences.append(f"Its verified company site features {pages_count} captured pages and {social_count} verified social links.")
    if news:
        sentences.append("Company-published news/press updates were found on its verified site.")

    # Hiring signal
    hiring_obs = row.get("_hiring_observation")
    if hiring_obs:
        h_metrics = hiring_obs.get("metrics") or {}
        if h_metrics.get("hiring_keyword_detected"):
            sentences.append("Maintains a careers/jobs page on its verified website with active hiring language detected.")
        else:
            sentences.append("Maintains a careers/jobs page on its verified website.")
        supporting_sources.append({
            "claim": "hiring_signal",
            "source_url": hiring_obs.get("source_url"),
            "retrieved_at": hiring_obs.get("retrieved_at"),
        })
    else:
        hiring = _hiring_signal(row)
        if hiring:
            sentences.append(f"It {hiring}.")

    nav_obs = row.get("_nav_observation")
    if nav_obs:
        nav_metrics = nav_obs.get("metrics") or {}
        job_t = nav_metrics.get("job_title") or "job opening"
        muni = nav_metrics.get("municipal") or ""
        muni_str = f" in {muni}" if muni else ""
        sentences.append(f"Public job vacancy listed on NAV Arbeidsplassen: '{job_t}'{muni_str}.")
        supporting_sources.append({
            "claim": "job_postings",
            "source_url": nav_obs.get("source_url"),
            "retrieved_at": nav_obs.get("retrieved_at"),
        })

    if refresh_events:
        relevant = [event for event in refresh_events if event.get("organisation_number") == org]
        if relevant:
            described = "; ".join(f"{event.get('change_type', 'change')} ({event.get('materiality', 'unspecified materiality')})" for event in relevant)
            sentences.append(f"Since the previous run: {described}.")
        else:
            sentences.append("No material change was detected since the previous run.")

    if unknowns:
        sentences.append("Not established in this run: " + "; ".join(unknowns))

    return {
        "organisation_number": org,
        "name": name,
        "summary": " ".join(sentences),
        "unsupported_or_uncertain": unknowns,
        "supporting_sources": supporting_sources,
        "generation_method": "deterministic_template_v1",
        "generated_at": utc_now(),
        "note": "Every sentence is a direct readout of an already-verified evidence field. No model was used; nothing here can invent a fact or an identity match.",
    }


def _index_by_org(path: str | None) -> dict[str, dict[str, Any]]:
    if not path or not Path(path).exists():
        return {}
    return {str(item["organisation_number"]): item for item in read_jsonl(Path(path))}


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a free, deterministic decision-useful summary per company profile.")
    parser.add_argument("--input", required=True, help="Terminal envelope or profile JSONL (must include the 'evidence' object)")
    parser.add_argument("--output", required=True)
    parser.add_argument("--refresh-events", help="Optional refresh-replay JSON (from run_refresh_replay.py) to fold change events into the summary")
    parser.add_argument("--activity", help="Optional activity connector JSONL")
    parser.add_argument("--news", help="Optional news connector JSONL")
    parser.add_argument("--hiring", help="Optional hiring connector JSONL")
    parser.add_argument("--wikidata", help="Optional wikidata connector JSONL")
    parser.add_argument("--nominatim", help="Optional nominatim connector JSONL")
    parser.add_argument("--nav", help="Optional nav connector JSONL")
    args = parser.parse_args()

    rows = read_jsonl(Path(args.input))
    activity_by_org = _index_by_org(args.activity)
    news_by_org = _index_by_org(args.news)
    hiring_by_org = _index_by_org(args.hiring)
    wikidata_by_org = _index_by_org(args.wikidata)
    nominatim_by_org = _index_by_org(args.nominatim)
    nav_by_org = _index_by_org(args.nav)

    for row in rows:
        org = str(row.get("organisation_number"))
        if org in activity_by_org:
            row["_activity_observation"] = activity_by_org[org]
        if org in news_by_org:
            row["_news_observation"] = news_by_org[org]
        if org in hiring_by_org:
            row["_hiring_observation"] = hiring_by_org[org]
        if org in wikidata_by_org:
            row["_wikidata_observation"] = wikidata_by_org[org]
        if org in nominatim_by_org:
            row["_nominatim_observation"] = nominatim_by_org[org]
        if org in nav_by_org:
            row["_nav_observation"] = nav_by_org[org]

    refresh_events = None
    if args.refresh_events:
        payload = json.loads(Path(args.refresh_events).read_text(encoding="utf-8"))
        refresh_events = payload.get("events", [])

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as handle:
        for row in rows:
            summary = build_summary(row, refresh_events)
            handle.write(json.dumps(summary, ensure_ascii=False, separators=(",", ":")) + "\n")
    print(f"Wrote {len(rows)} synthesis summaries to {out_path}")


if __name__ == "__main__":
    main()
